services:
  grpc.service:
    image: ${DOCKER_NAMESPACE-}grpc.service:${VERSION}
    build:
      context: ./server
      dockerfile: Grpc.Service/Dockerfile
      args:
        - AUTHORS=${AUTHORS}
        - VERSION=${VERSION}
        - TITLE=${TITLE}
        - DESCRIPTION=${DESCRIPTION}
    ports:
      - 9020:8081
    healthcheck:
      # This command runs inside the container to check the gRPC endpoint
      test: ["CMD-SHELL", "/usr/local/bin/grpc_health_probe", "-tls -tls-no-verify -addr=localhost:8081"] 
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - grpc_service_network
    restart: unless-stopped
    environment:
      - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=True
    depends_on:
      mssql:
        condition: service_healthy
      seq:
        condition: service_started
      redis:
        condition: service_healthy
    volumes:
      - grpc_service_logs:/app/logs/grpc/
  
  redis:
    image: redis@sha256:6cbef353e480a8a6e7f10ec545f13d7d3fa85a212cdcc5ffaf5a1c818b9d3798
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 3s
      retries: 3
    command: ["redis-server"]
    networks:
      - grpc_service_network
    volumes:
      - grpc_redis_data:/data
 
  mssql:
    image: mcr.microsoft.com/mssql/server@sha256:db9a8fe3098b7e8bbde41106bdc7caee942e97124e5fdb71b872ca208de3092d
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -U sa -P \"${MSSQL_SA_PASSWORD}\" -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - 1436:1433
    networks:
      - grpc_service_network
    restart: unless-stopped
    volumes:
      - mssql_data:/var/opt/mssql

  seq:
    image: datalust/seq:latest
    ports:
      - 5341:5341
      - 8081:80
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_FIRSTRUN_ADMINPASSWORD}
    networks:
      - grpc_service_network 
    restart: unless-stopped
    volumes:
      - seq_data:/data

networks:
  grpc_service_network:
    driver: bridge

volumes:
  mssql_data:
  grpc_service_logs:
  seq_data:
  grpc_redis_data:
